Repository Projetos-UNICAMP/voluntariapp, pull requests merged in 2023-12, with the labels that each got.

#45 Fix: Corrige Lint
  src/Components/AppLogo/AppLogo.stories.tsx
  src/Components/FinalButton/FinalButton.stories.tsx
  src/Components/FinalButton/FinalButton.tsx
  src/Components/FinalDropDown/FinalDropDown.stories.tsx
  src/Components/FinalTextInputField/FinalTextInputField.stories.tsx
  src/Components/SimpleText/SimpleText.stories.tsx
  src/Components/SimpleText/SimpleText.tsx
  src/Components/TitleText/TitleText.stories.tsx
  src/Components/TopMenu/TopMenu.tsx
  src/Layouts/RigthImageLayout/RigthImageLayout.stories.tsx
  src/api/firebaseImp/eventos.service.test.ts
  src/pages/CreateEventPage.tsx
  src/pages/EventInfo.tsx
Labels: AvaliacaoA2

#46 Release: v1.0.0
  .eslintrc.cjs
  .github/workflows/pipeline.yml
  .storybook/main.ts
  .storybook/preview.tsx
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/Components/AppLogo/AppLogo.stories.tsx
  src/Components/AppLogo/AppLogo.tsx
  src/Components/FinalButton/FinalButton.stories.tsx
  src/Components/FinalButton/FinalButton.tsx
  src/Components/FinalDropDown/FinalDropDown.stories.tsx
  src/Components/FinalDropDown/FinalDropDown.tsx
  src/Components/FinalTextInputField/FinalTextInputField.stories.tsx
  src/Components/FinalTextInputField/FinalTextInputField.tsx
  src/Components/SimpleText/SimpleText.stories.tsx
  src/Components/SimpleText/SimpleText.tsx
  src/Components/TitleText/TitleText.stories.tsx
  src/Components/TitleText/TitleText.tsx
  src/Components/TopMenu/TopMenu.tsx
  src/Layouts/RigthImageLayout/RigthImageLayout.stories.tsx
  src/Layouts/RigthImageLayout/RigthImageLayout.tsx
  src/api/eventos.api.ts
  src/api/firebaseImp/eventos.service.test.ts
  src/api/firebaseImp/usuarios.service.test.ts
  src/api/usuarios.api.ts
  src/assets/blob.png
  src/assets/cuted.png
  src/assets/discs.png
  src/assets/pens.png
  src/assets/react.svg
  src/assets/title.png
  src/index.css
  src/main.tsx
  src/pages/CreateEventPage.tsx
  src/pages/EventInfo.tsx
  src/pages/LandingPage.tsx
  src/pages/SignUpPage.tsx
  src/routes/routes.tsx
  tsconfig.json
Labels: Release

#50 Refactor/gerenciamento erros
  src/api/errorHandler.ts
  src/api/firebaseImp/eventos.service.ts
  src/api/firebaseImp/usuarios.service.ts
Labels: AvaliacaoA4

#48 Remove comentarios reduntantes dos serviços
  src/api/firebaseImp/eventos.service.ts
  src/api/firebaseImp/usuarios.service.ts
Labels: AvaliacaoA4

#49 Adiciona arquivo de config para variaveis
  src/api/firebaseImp/configuration.ts
  src/api/firebaseImp/eventos.service.ts
  src/api/firebaseImp/usuarios.service.ts
Labels: AvaliacaoA4

#53 Implementando o padrao façade na pagina de eventos EventInfo, diverso…
  package-lock.json
  src/Components/BackButton/BackButton.tsx
  src/Components/LoadingSpinner/LoadingSpinner.tsx
  src/Components/SimpleText/SimpleText.tsx
  src/Components/TitleText/TitleText.tsx
  src/Components/TopMenu/TopMenu.tsx
  src/Components/WideBlob/WideBlob.tsx
  src/index.css
  src/pages/EventInfo.tsx
  src/pages/LandingPage.tsx
  src/pages/SignUpPage.tsx
Labels: AvaliacaoA4

#61 Feat/inscrever em evento
  src/Components/FinalButton/FinalButton.tsx
  src/Components/ShiftCard/ShiftCard.tsx
  src/Components/TitleText/TitleText.tsx
  src/Components/TopMenu/TopMenu.tsx
  src/api/eventos.api.ts
  src/api/firebaseImp/eventos.service.ts
  src/pages/CreateEventPage.tsx
  src/pages/EventInfo.tsx
Labels: Feature

#64 Corrige erros do linter
  src/api/firebaseImp/eventos.service.test.ts
  src/main.tsx
Labels: bug

#65 Altera testes
  src/api/firebaseImp/eventos.service.test.ts
Labels: bug
